spring:
  datasource:
    url: jdbc:mysql://47.111.112.220:3306/socks?useSSL=false
    username: root
    password: 19961001@Zmm
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
   map-underscore-to-camel-case: true #开启驼峰映射

